"""Phase 31 — secure trust-key storage tests."""
from __future__ import annotations

import tempfile
from pathlib import Path

import pytest


def test_file_key_provider_loads_existing():
    from satsa.analysis.trust_storage import FileKeyProvider
    with tempfile.TemporaryDirectory() as td:
        p = FileKeyProvider(Path(td) / "keys")
        kp1 = p.load_or_create()
        # Re-instantiate — should load the same key
        p2 = FileKeyProvider(Path(td) / "keys")
        kp2 = p2.load_or_create()
        assert kp1.public_key == kp2.public_key
        assert kp1.secret_key == kp2.secret_key


def test_file_key_provider_creates_new():
    from satsa.analysis.trust_storage import FileKeyProvider
    with tempfile.TemporaryDirectory() as td:
        p = FileKeyProvider(Path(td) / "keys")
        kp = p.load_or_create()
        assert len(kp.public_key) > 0
        assert len(kp.secret_key) > 0
        # File exists
        assert (Path(td) / "keys" / "satsa_trust_key.json").exists()


def test_keystore_key_provider_roundtrip():
    """The keystore-backed provider seals the key in a vault and
    can unseal it with the correct passphrase."""
    from satsa.analysis.trust_storage import KeystoreKeyProvider
    with tempfile.TemporaryDirectory() as td:
        p1 = KeystoreKeyProvider(Path(td) / "keys", "test-passphrase-1")
        kp1 = p1.load_or_create()
        # Re-instantiate with same passphrase
        p2 = KeystoreKeyProvider(Path(td) / "keys", "test-passphrase-1")
        kp2 = p2.load_or_create()
        assert kp1.public_key == kp2.public_key
        assert kp1.secret_key == kp2.secret_key


def test_keystore_key_provider_wrong_passphrase_fails():
    from satsa.analysis.trust_storage import KeystoreKeyProvider
    with tempfile.TemporaryDirectory() as td:
        p1 = KeystoreKeyProvider(Path(td) / "keys", "correct")
        p1.load_or_create()
        # Wrong passphrase must fail
        p2 = KeystoreKeyProvider(Path(td) / "keys", "wrong")
        with pytest.raises(Exception):
            p2.load_or_create()


def test_both_providers_yield_same_key_material():
    """A key generated by FileKeyProvider and a key generated by
    KeystoreKeyProvider should both work as ML-DSA signing keys
    (the bytes are independent, but both must verify a signature)."""
    from satsa.analysis.trust_storage import FileKeyProvider, KeystoreKeyProvider
    from qsmlops.crypto.providers import SIGNATURE_PROVIDERS
    with tempfile.TemporaryDirectory() as td:
        kp_file = FileKeyProvider(Path(td) / "f").load_or_create()
        kp_ks = KeystoreKeyProvider(Path(td) / "k", "pass").load_or_create()
        prov = SIGNATURE_PROVIDERS[kp_file.algorithm_id]
        msg = b"test message"
        sig_f = prov.sign(kp_file.secret_key, msg)
        sig_k = prov.sign(kp_ks.secret_key, msg)
        # Both signatures verify against their own public keys
        assert prov.verify(kp_file.public_key, msg, sig_f)
        assert prov.verify(kp_ks.public_key, msg, sig_k)
        # Cross-verification must fail (different keys)
        assert not prov.verify(kp_ks.public_key, msg, sig_f)
        assert not prov.verify(kp_file.public_key, msg, sig_k)
