"""Supervisory assessment report renderer — produces a self-contained
HTML report for one entity's latest run. Used by the UI's
``/reports/{entity_id}`` route and the demo flow.
"""
from __future__ import annotations

import html
import time
from typing import Iterable


def _satsa_version() -> str:
    from satsa import __version__
    return __version__


def _esc(s) -> str:
    return html.escape(str(s)) if s is not None else ""


def _confidence_block(conf: dict) -> str:
    if not conf:
        return "<em>no confidence</em>"
    parts = []
    for k in ("analytical_support", "evidence_completeness", "peer_confidence"):
        v = conf.get(k)
        if v is not None:
            parts.append(f"<dt>{_esc(k)}</dt><dd>{v:.2f}</dd>")
    if "overall" in conf:
        parts.append(f"<dt>overall</dt><dd>{conf['overall']:.2f}</dd>")
    return "<dl>" + "".join(parts) + "</dl>"


def render_report(*, entity: dict, assessments: list[dict],
                  risk, findings: list[dict], generated_at: float) -> str:
    """Return a self-contained HTML report (no external assets) for
    one entity's latest run. The result is intended to be printable
    / shareable as a single artifact."""
    rows = ""
    for f in findings:
        confidence = {}
        try:
            import json as _json
            confidence = _json.loads(f.get("confidence_json") or "{}")
        except Exception:
            pass
        rows += (
            "<tr>"
            f"<td><code>{_esc(f.get('rule_or_category',''))}</code></td>"
            f"<td>{_esc(f.get('state',''))}</td>"
            f"<td>{_esc(f.get('rationale',''))}</td>"
            f"<td>{_esc(f.get('worker_name',''))}</td>"
            f"<td>{_confidence_block(confidence)}</td>"
            "</tr>")
    assessment_block = ""
    if assessments:
        a = assessments[0]
        assessment_block = (
            f"<p><strong>Assessment period:</strong> "
            f"{_esc(a.get('period_start'))} → {_esc(a.get('period_end'))} "
            f"({_esc(a.get('status',''))})</p>")
    risk_block = ""
    if risk is not None and risk.run_id is not None:
        d = risk.to_dict()
        rows2 = "".join(
            f"<tr><td>{_esc(d['name'])}</td><td>{d['weight']}</td>"
            f"<td>{d['score']:.1f}</td><td>{_esc(d['rationale'])}</td></tr>"
            for d in d["dimensions"])
        risk_block = (
            f"<h2>Risk</h2>"
            f"<p><strong>Total: {d['total_score']:.1f} / 100</strong> "
            f"(confidence: {_esc(d['confidence_bucket'])})</p>"
            "<table border='1' cellpadding='4' cellspacing='0'>"
            "<tr><th>Dimension</th><th>Weight</th><th>Score</th><th>Rationale</th></tr>"
            f"{rows2}</table>")
    return f"""<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<title>SAT-SA Assessment — {_esc(entity.get('display_name',''))}</title>
<style>
body {{ font-family: -apple-system, system-ui, sans-serif; max-width: 1100px;
       margin: 2em auto; padding: 0 1em; color: #1a1a1a; }}
h1, h2, h3 {{ color: #0b3d91; }}
table {{ border-collapse: collapse; width: 100%; margin: 1em 0; }}
th, td {{ border: 1px solid #ccc; padding: 0.4em 0.6em; text-align: left;
        vertical-align: top; }}
th {{ background: #f3f6fb; }}
code {{ background: #f3f6fb; padding: 0.05em 0.3em; border-radius: 3px; }}
dt {{ font-weight: 600; }}
</style></head><body>
<h1>SAT-SA Assessment — {_esc(entity.get('display_name',''))}</h1>
<p>Generated by SAT-SA v{_esc(_satsa_version())} at
 {_esc(time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime(generated_at)))}</p>
<h2>Entity</h2>
<table>
<tr><th>Name</th><td>{_esc(entity.get('display_name',''))}</td></tr>
<tr><th>Sector</th><td>{_esc(entity.get('sector',''))}</td></tr>
<tr><th>Environment</th><td>{_esc(entity.get('environment_class',''))}</td></tr>
</table>
{assessment_block}
{risk_block}
<h2>Findings ({len(findings)})</h2>
<table>
<tr><th>Rule</th><th>State</th><th>Rationale</th><th>Worker</th><th>Confidence</th></tr>
{rows}
</table>
</body></html>"""
