"""PostgreSQL DDL mapping for the existing versioned SQLite schema.

One migration history owns both dialects. The mapping is deliberately limited
to the three SQLite types/syntax forms present in that history; unsupported
SQLite constructs must fail validation rather than being silently skipped.
"""
from __future__ import annotations

import re


_AUTOINCREMENT = re.compile(r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b", re.I)
_REAL = re.compile(r"\bREAL\b", re.I)
_BLOB = re.compile(r"\bBLOB\b", re.I)
_UNSUPPORTED = re.compile(r"\b(?:AUTOINCREMENT|PRAGMA|WITHOUT\s+ROWID)\b", re.I)


def postgres_statement(sql: str) -> str:
    statement = _AUTOINCREMENT.sub("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql)
    statement = _REAL.sub("DOUBLE PRECISION", statement)
    statement = _BLOB.sub("BYTEA", statement)
    if _UNSUPPORTED.search(statement):
        raise ValueError("unsupported SQLite construct in PostgreSQL migration")
    return statement
