/**
 * DEVELOPMENT ONLY. Serves the SAT-SA development fixture through the
 * SatsaDataSource interface so every screen is explorable before the
 * backend API exists.
 *
 * The fixture (./fixture.json) is not hand-written: it is generated by
 * web/scripts/export-demo-fixture.py from a real backend run over the
 * committed synthetic demo dataset. Regenerate it rather than editing it.
 * It contains no review decisions because the backend demo records none.
 *
 * Server-only: import through src/lib/api/index.ts, never from a client
 * component (it would ship the whole fixture to the browser).
 */
import "server-only";

import type { FindingQuery, SatsaDataSource } from "@/lib/api/source";
import type {
  AgentSpec,
  AnalysisRun,
  Assessment,
  Entity,
  EntityPriority,
  EntityRiskProfile,
  Finding,
  MetaAudit,
  Observation,
  RunVerification,
  SecurityData,
  SourceRecord,
  Submission,
  SupervisorDecision,
  TrustReceipt,
  ValidationReport,
  WorkerJob,
} from "@/lib/types/domain";
import raw from "./fixture.json";

interface Fixture {
  meta: { generatedAt: number; notice: string; satsaVersion: string };
  riskWeights: Record<string, number>;
  entities: Entity[];
  assessments: Assessment[];
  submissions: Submission[];
  runs: AnalysisRun[];
  jobs: WorkerJob[];
  observations: Observation[];
  findings: Finding[];
  riskProfiles: Record<string, EntityRiskProfile>;
  entityPriorities: EntityPriority[];
  trustReceipts: TrustReceipt[];
  verifications: Record<string, RunVerification>;
  sourceRecords: SourceRecord[];
  securityData: SecurityData;
  agents: AgentSpec[];
  supervisorDecisions: Record<string, SupervisorDecision>;
  metaAudit: MetaAudit;
  validation: ValidationReport;
}

const fx = raw as unknown as Fixture;
const ok = <T,>(value: T) => Promise.resolve(value);

export const fixtureSource: SatsaDataSource = {
  origin: () => ({
    kind: "fixture",
    generatedAt: fx.meta.generatedAt,
    notice: fx.meta.notice,
    satsaVersion: fx.meta.satsaVersion,
  }),

  listEntities: () => ok(fx.entities),
  getEntity: (id) => ok(fx.entities.find((e) => e.id === id) ?? null),
  listAssessments: (entityId) => ok(entityId ? fx.assessments.filter((a) => a.entityId === entityId) : fx.assessments),
  listSubmissions: (entityId) => ok(entityId ? fx.submissions.filter((s) => s.entityId === entityId) : fx.submissions),

  listRuns: (entityId) => ok(entityId ? fx.runs.filter((r) => r.entityId === entityId) : fx.runs),
  listJobs: (runId) => ok(runId ? fx.jobs.filter((j) => j.runId === runId) : fx.jobs),
  listObservations: (runId) => ok(runId ? fx.observations.filter((o) => o.runId === runId) : fx.observations),

  listFindings: (query?: FindingQuery) =>
    ok(
      fx.findings.filter(
        (f) =>
          (!query?.entityId || f.entityId === query.entityId) &&
          (!query?.runId || f.runId === query.runId) &&
          (!query?.state || f.state === query.state),
      ),
    ),
  getFinding: (id) => ok(fx.findings.find((f) => f.id === id) ?? null),

  getRiskProfile: (entityId) => ok(fx.riskProfiles[entityId] ?? null),
  listEntityPriorities: () => ok(fx.entityPriorities),
  getRiskWeights: () => ok(fx.riskWeights),

  // The backend demo records no human decisions; the fixture carries none.
  listReviewDecisions: () => ok([]),

  listTrustReceipts: (subjectId) =>
    ok(subjectId ? fx.trustReceipts.filter((t) => t.subjectId === subjectId) : fx.trustReceipts),
  getRunVerification: (runId) => ok(fx.verifications[runId] ?? null),
  getMetaAudit: () => ok(fx.metaAudit),

  listSourceRecords: (ids) => ok(ids ? fx.sourceRecords.filter((s) => ids.includes(s.id)) : fx.sourceRecords),
  getSecurityData: (entityId) => {
    if (!entityId) return ok(fx.securityData);
    const d = fx.securityData;
    const caseIds = new Set(d.cases.filter((c) => c.entityId === entityId).map((c) => c.id));
    return ok({
      alerts: d.alerts.filter((a) => a.entityId === entityId),
      cases: d.cases.filter((c) => c.entityId === entityId),
      investigationSteps: d.investigationSteps.filter((s) => caseIds.has(s.caseId)),
      escalations: d.escalations.filter((e) => e.entityId === entityId),
      dispositions: d.dispositions.filter((x) => x.entityId === entityId),
      assets: d.assets.filter((a) => a.entityId === entityId),
    });
  },

  listAgents: () => ok(fx.agents),
  getSupervisorDecision: (runId) => ok(fx.supervisorDecisions[runId] ?? null),
  getValidation: () => ok(fx.validation),
};
