"use server";

import { revalidatePath } from "next/cache";
import { api } from "@/lib/api/client";
import type { ActionResult } from "@/lib/api/errors";
import { act } from "@/lib/api/guard";
import {
  EVIDENCE_CATEGORIES,
  type Artifact,
  type Assessment,
  type Decision,
  type DecisionAction,
  type Entity,
  type EvidenceCategory,
  type Invitation,
  type MembershipRole,
  type Run,
  type Submission,
  type Validation,
  type Verification,
  type Version,
} from "@/lib/api/types";

/**
 * Every write the workbench performs, one backend route each
 * (docs/API_CONTRACT.md). Idempotency keys are generated by the caller per
 * logical step and reused on retry, so a repeated click returns the original
 * resource instead of creating a second one.
 */

const text = (v: FormDataEntryValue | null) => (typeof v === "string" ? v.trim() : "");

export async function createEntityAction(input: { display_name: string; sector: string; environment_class: string }): Promise<ActionResult<Entity>> {
  const r = await act(() => api.createEntity(input));
  if (r.ok) revalidatePath("/workbench", "layout");
  return r;
}

export async function createAssessmentAction(input: { entity_id: string; period_start: number; period_end: number }): Promise<ActionResult<Assessment>> {
  return act(() => api.createAssessment(input));
}

export async function createSubmissionAction(assessmentId: string, key: string): Promise<ActionResult<Submission>> {
  return act(() => api.createSubmission(assessmentId, key));
}

export async function createVersionAction(submissionId: string, key: string): Promise<ActionResult<Version>> {
  return act(() => api.createVersion(submissionId, key));
}

/** multipart: version_id, category, key, file */
export async function uploadArtifactAction(form: FormData): Promise<ActionResult<Artifact>> {
  const versionId = text(form.get("version_id"));
  const category = text(form.get("category")) as EvidenceCategory;
  const key = text(form.get("key"));
  const file = form.get("file");
  if (!(file instanceof File) || !EVIDENCE_CATEGORIES.includes(category) || !versionId || !key) {
    return { ok: false, error: { status: 422, code: "VALIDATION_ERROR", message: "A file, a category and a submission version are required.", requestId: "", details: [] } };
  }
  return act(() => api.uploadArtifact(versionId, category, file, key));
}

export async function completeVersionAction(versionId: string): Promise<ActionResult<Version>> {
  return act(() => api.completeVersion(versionId));
}

export async function validateVersionAction(versionId: string): Promise<ActionResult<Validation>> {
  const r = await act(() => api.validateVersion(versionId));
  if (r.ok) revalidatePath("/workbench/submissions");
  return r;
}

export async function startRunAction(versionId: string, mode: "graph" | "standard", key: string): Promise<ActionResult<Run>> {
  const r = await act(() => api.startRun(versionId, mode, key));
  if (r.ok) revalidatePath("/workbench", "layout");
  return r;
}

export async function cancelRunAction(runId: string): Promise<ActionResult<Run>> {
  const r = await act(() => api.cancelRun(runId));
  if (r.ok) revalidatePath(`/workbench/runs/${runId}`);
  return r;
}

export async function decideAction(runId: string, action: DecisionAction, reason: string): Promise<ActionResult<Decision>> {
  const r = await act(() => api.decide(runId, action, reason));
  if (r.ok) revalidatePath("/workbench", "layout");
  return r;
}

export async function verifyAction(runId: string): Promise<ActionResult<Verification>> {
  return act(() => api.verify(runId));
}

export async function inviteMemberAction(input: { name: string; email: string; role: MembershipRole }): Promise<ActionResult<Invitation>> {
  const r = await act(() => api.inviteMember(input));
  if (r.ok) revalidatePath("/workbench/admin");
  return r;
}

export async function revokeMemberAction(userId: string): Promise<ActionResult<null>> {
  const r = await act(async () => {
    await api.revokeMember(userId);
    return null;
  });
  if (r.ok) revalidatePath("/workbench/admin");
  return r;
}
